services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - dev

volumes:
  qdrant_storage:

networks:
  dev:
    driver: bridge
