services:
  postgres:
    image: postgres:17.0
    # restart: always
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres-data17:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data17:

networks:
  dev:
    driver: bridge
# server connection-string jdbc:postgresql://localhost:5432/databasename
