version: "3.8"

services:
  postgres:
    image: postgres:16.2-alpine3.19
    # restart: always
    environment:
      POSTGRES_DB: postgresDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres-data16:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data16:

networks:
  dev:
    driver: bridge
# server connection-string jdbc:postgresql://localhost:5432/databasename
