services:
  redis:
    image: bitnami/redis:6.2.10
    # restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - dev

volumes:
  redis-data:
    driver: local

networks:
  dev:
    driver: bridge
